# The name of your barrel. Any barrel renamed to this in an anvil
# will be treated as a Post Box
custom-barrel-name: "pobox"

# Display mail state on post box signs. When enabled, a notification will be
# added to the third line of the post box sign
sign-notification: true

# Do we want to delay the got-mail-message by 10 seconds? This ensures the message
# isn't lost in any other messages they receive during connection
got-mail-delay: true

# Do you want to use the built-in protection to prevent players breaking
# Post Boxes? Disable if you prefer to use something like WorldGuard
postbox-protection: true

# Hopper protection stops items being removed from your post boxes
# Disabled by default as this can cause lag with excessive amounts of hoppers
hopper-protection: false

# Do you want to check for updates when restarting the server?
# This will also message any server ops to notify them each time they log on.
update-notification: true

# Do you want to print messages to the server console? You'll always receive
# start up/shut down messages as well as warnings/errors. Disabling this will
# remove the less important console logs like the mail file being updated etc.
console-logs: false

# Having plugin issues? Enable debug logs to help troubleshoot issues
# These extra detailed messages are printed to the console only
debug: false

# Maximum number of secondary post boxes a player can have at their bases/homes
# These boxes act as remote access points to their main post office box
# Set to -1 for unlimited secondary boxes
max-secondary-boxes: 5

# Number of days players can view their mail history (/postoffice history)
# Players will only see items deposited into their box within this timeframe
# Set to -1 to show all history with no time limit
player-history-days: 30

# Number of days to retain all logs before purging them
# This applies to all admin logs (/postoffice log)
# Set to -1 to never purge logs (keep forever)
log-retention-days: 90


# Config file version
# Do not manually change this setting
# Used to update out of date config files
config-version: 2